### ISSUE TITLE
ImportError: No module named 'cflib.fasta'

### ISSUE THREAD

**Issue by fishextinction** [pomo-dev/cflib#1]
Installed cflib with easy_install3 on both a Linux and an OS X machine.

I get this error when I try to run a script:

python FastaToCounts.py --help
Traceback (most recent call last):
  File "FastaToCounts.py", line 13, in <module>
    import cflib.fasta as fa
ImportError: No module named 'cflib.fasta'

I'm sure this is probably an issue with installing cflib. I'd appreciate a more detailed guide.

**Comment by dschrempf** [comment]
Hi,

Thank you very much for your interest in PoMo! I also believe that the installation of the library did not complete properly. Can you post the exact command that you used to install `cflib`?

If I run `easy_install` from within the `cflib` folder (please note the `.`)

    easy_install --user .

I get an output of

    Processing .
    Writing /home/dominik/temp/cflib/setup.cfg
    Running setup.py -q bdist_egg --dist-dir /home/dominik/temp/cflib/egg-dist-tmp-je82qer6
    zip_safe flag not set; analyzing archive contents...
    Moving cflib-1.0-py3.6.egg to /home/dominik/.local/lib/python3.6/site-packages
    Adding cflib 1.0 to easy-install.pth file
    Installing CountsToFasta.py script to /home/dominik/.local/bin
    Installing FastaToCounts.py script to /home/dominik/.local/bin
    Installing FastaToVCF.py script to /home/dominik/.local/bin
    Installing FastaVCFToCounts.py script to /home/dominik/.local/bin
    Installing FilterMSA.py script to /home/dominik/.local/bin
    Installing GPToCounts.py script to /home/dominik/.local/bin
    Installing MSAToCounts.py script to /home/dominik/.local/bin

    Installed /home/dominik/.local/lib/python3.6/site-packages/cflib-1.0-py3.6.egg
    Processing dependencies for cflib==1.0
    Finished processing dependencies for cflib==1.0

And I can run the conversion script

     FastaToCounts.py --help

     usage: FastaToCounts.py [-h] [-v] [--iupac] fastaFile output
     .
     .
     .

**Comment by fishextinction** [comment]
I was able to successfully install using 

`sudo easy_install3 --user . 
`
on the latest Ubuntu version.

Given the ubiquity of Python 2.7, particularly on OS X, you might consider updating the guide so that it uses tools specifically for Python 3.x so people don't accidentally install to the wrong Python version. The software looks really cool, but I suspect I'm not the first biologist to have this issue.

**Comment by dschrempf** [comment]
I will change the README so that it is more clear with respect to Python 3.

You should not need to use `sudo` when installing the library in the `--user` directory. But I am glad that you got it to work!
