### ISSUE TITLE
FastaVCFToCounts.py error

### ISSUE THREAD

**Issue by wcfgit** [pomo-dev/cflib#3]
Hello!

I have been trying to make a count file using the above-mentioned script (installed via pip3).
First, I have created one vcf per population/species (using vcftools), then I used the script as follows:

FastaVCFToCounts.py reference.fasta Pop1.vcf.gz Pop2.vcf.gz Pop3.vcf.gz Pop4.vcf.gz test.counts.gz -p 1 -m

but I am getting the following error:

File "/home/wagner/.local/bin/FastaVCFToCounts.py", line 114, in <module>
    cfw.write_Rn(rg)
  File "/home/wagner/.local/lib/python3.6/site-packages/cflib/cf.py", line 1002, in write_Rn
    self.__fill_cD(iL, snpL)
  File "/home/wagner/.local/lib/python3.6/site-packages/cflib/cf.py", line 896, in __fill_cD
    bI = dna[altBases[spData[i][d]-1]]
KeyError: '*'

What could be the mistake here?

Thank you in advance!

**Comment by dschrempf** [comment]
Hi!

I think this is because your VCF files use a code letter that is not a standard
IUPAC code ('*'). I guess this letter means that the base is unknown? I added a
commit to the library so that these letters are ignored. No count will be added
to the counts file.

Let me know if it works or if you have any other questions!

Dominik

**Comment by wcfgit** [comment]
Hello Dominik,

Thank you very much for your answer and for the new commit.
The new script worked just fine!

I was wondering that it may be because in some sites I have multiallelic SNPs - may be this the reason?
If so, it would be good to add a note on that if possible.

Anyways, thank you very much for the help!

**Comment by dschrempf** [comment]
Hm, I don't really know why your VCF files have this star. Usually, it is used when the base is unknown. But it is a non-standard code. The standard would be either `N` for unknown (or any base), and `-` or `.` for a gap or a deletion. I add a note to the README! Please reopen the issue, if you think it is not clear enough.
