### ISSUE TITLE
Possibility of converting .vcf file to .fasta ?

### ISSUE THREAD

**Issue by tviguier** [pomo-dev/cflib#4]
Hello Mr Schrempf,

I am a student at the Ngere laboratory in Nancy and as part of my internship, I have to convert fasta files into a .vcf file in order to keep only the mutations present in the sequences, a step that can be carried out using your python script FastaToVCF.py, script allowing to convert only one fasta sequence at a time if it is exact.

But then I am asked from the .vcf files obtained, to convert them into fasta and therefore obtain the fasta sequences with the mutations included.

Do you know if this is possible with your scripts? by digging into the different scripts in the cflib folder and rearranging for example.

Thank you in advance for your answer !

**Comment by dschrempf** [comment]
Hello. At the moment, I do not provide this feature as a ready made script, but you could use the library to do such a task yourself. However, there may be libraries available that are more tailored to your task! Sorry that I cannot help you in a better way.

**Comment by tviguier** [comment]
Ok ! thank you for the information and thank you for answering me so quickly !
