### ISSUE TITLE
FastaToCounts.py not stripping population names as intended

### ISSUE THREAD

**Issue by Bantamajorus** [pomo-dev/cflib#5]
Hi,

First of all thank you for making available this software.

When I coded my identifiers as follows: for example '>pop1-subpop1-ind1' the identifier was stripped at the _second_ dash, instead of the first dash (which is how it is supposed to work according to the documentation).

Cheers

**Comment by dschrempf** [comment]
Hi!

Thank your for bringing this to my attention. This should be fixed, please let me know, if you have problems!
