### ISSUE TITLE
Error message: Sequence 2 has different length than reference

### ISSUE THREAD

**Issue by MehdiiYac** [pomo-dev/cflib#6]
Hello i am trying to convert a fasta file to a vcf one using this tool. But i keep getting the same error:
raise sb.SequenceDataError(cflib.seqbase.SequenceDataError: Sequence 2 has different length than reference.

How can i solve it?

**Comment by dschrempf** [comment]
Hello!

It is hard to say what your problem is without a detailed description. All I can say at the moment is that the error is thrown here: https://github.com/pomo-dev/cflib/blob/master/cflib/fasta.py#L854. I think your FASTA file has sequences of different length. Is this so?

**Comment by MehdiiYac** [comment]
Hi, thanks for your answer
I think that's the case because i got the same error with all 3 of my fa files, is there anything I can do about it or a way to go around it?
Thanks.

**Comment by dschrempf** [comment]
You need to make sure that your sequences have  euqal lengths, otherwise the script doesn't know which sites correspond to each other.

**Comment by NicolaDM** [comment]
One way to do that is to use a multiple sequence alignment software such as MAFFT https://mafft.cbrc.jp/alignment/software/  on your fasta file. The output you get is still a fasta file, but this time all sequences have the same length thanks to gap characters that the aligner adds to them.
The specific aligner you might want to use might depend on your data, but for datasets of small to medium size MAFFT is usually ok.

**Comment by dschrempf** [comment]
Thanks Nicola!
