### ISSUE TITLE
Error when running FastaVCFToCounts.py

### ISSUE THREAD

**Issue by sb2g14** [pomo-dev/cflib#7]
Hello

I'm running Python 3.11.14 on MacOS Monterrey.

When executing 

```vcf_files=(p1.vcf.gz p2.vcf.gz p3.vcf.gz p4.vcf.gz)```

```python3 FastaVCFToCounts.py anc.fa.gz "${vcf_files[@]}" example_from_fasta_vcf.cf --merge --ploidy 2```

I get error 
```
  File "/Users/sb442/Documents/work/DataConversion/cflib/cflib/cf.py", line 766, in __snp
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sb442/Documents/work/DataConversion/cflib/scripts/FastaVCFToCounts.py", line 122, in <module>
    cfw.write_Rn(rg)
  File "/Users/sb442/Documents/work/DataConversion/cflib/cflib/cf.py", line 1005, in write_Rn
    (nI, nSNP) = next(snpsG)
                 ^^^^^^^^^^^
RuntimeError: generator raised StopIteration
```

When I remove line 766 in *cf.py* `raise StopIteration()` everything seems to work fine. I get reasonable outputs but I'm not sure if this fix breaks anything else.

Many thanks
Svitlana

**Comment by dschrempf** [comment]
Hi! Thanks for using `cflib`. From the line counts I can see that you may be using an older version of `cflib`. Did you install the library using `pip`? If so, could you try the last version on this Git repository?

If you want, I can also publish a new version on pypi, but I do not have the time for this atm. I can do this probably on Wednesday. (It should be done anyways).

**Comment by sb2g14** [comment]
Many thanks for prompt reply. I run the the source code clonned from *GitHub*. Now updated but the error still persists.

Many thanks
Svitlana

**Comment by dschrempf** [comment]
Thanks. I will have a look tomorrow!

**Comment by dschrempf** [comment]
Hm, I just had a look, and I do not understand why the exception surfaces at runtime. All next() statements are correctly wrapped in a `try/except` block, so the StopIteration exception should be caught and handled.

```
        try:
            (nI, nSNP) = next(snpsG)
        except StopIteration:
            nI = None
            nSNP = None
```

Are you sure you are running the latest version? However, I also see that this part of the code has not changed recently. Which version of Python are you using?

**Comment by dschrempf** [comment]
Could you please update your bug report using the latest version, so that I know the line numbers exactly? Thank you!

**Comment by sb2g14** [comment]
Hi, many thanks for looking into this. I'm running Python 3.11.4 on MacOS Monterrey. Apology, I didn't realise that I changed the code slightly. The particular block of the code returning the error is
```
 while True:
            if snpL == [None] * self.nV:
                raise StopIteration()
```
The compiler complains about the line 760. I seems that the way of handling `StopIteration` exceptions changed since Python 3.7 release as mentioned in this [thread](https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app). Could that be the problem?

Best
Svitlana

**Comment by dschrempf** [comment]
Hi Svitlana, thanks for the updated report. I was more interested in the calling line which does not handle the StopIteration exception.

I also had had a look at https://peps.python.org/pep-0479/ when looking into this yesterday :-). It could be the reason but catching the exception should normally be OK. Thank you!

**Comment by sb2g14** [comment]
Hi, I tried to print `snpL` variable, hope it will help. Everything seems fine until it becomes all `None`. In that case the exception is not handled. Please see the updated report with the updated line numbers

```
snpL: [<cflib.vcf.NucBase object at 0x105271510>, <cflib.vcf.NucBase object at 0x11df72e90>, None, <cflib.vcf.NucBase object at 0x106edb390>]
snpL: [None, <cflib.vcf.NucBase object at 0x11df72e90>, None, <cflib.vcf.NucBase object at 0x106edb390>]
snpL: [None, None, None, <cflib.vcf.NucBase object at 0x106edb390>]
snpL: [None, None, None, None]
Traceback (most recent call last):
  File "/Users/sb442/Documents/work/DataConversion/cflib/cflib/cf.py", line 760, in __snp
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sb442/Documents/work/DataConversion/cflib/scripts/FastaVCFToCounts.py", line 114, in <module>
    cfw.write_Rn(rg)
  File "/Users/sb442/Documents/work/DataConversion/cflib/cflib/cf.py", line 993, in write_Rn
    (nI, nSNP) = next(snpsG)
                 ^^^^^^^^^^^
RuntimeError: generator raised StopIteration
```

**Comment by dschrempf** [comment]
Hm. In this case, I would need some minimal input files so that I can replcate the error. Please send them over privately, if you can.
